apiVersion: v1
kind: Service

metadata:
  name: person-api

spec:
  selector:
    app: person-api
  ports:
  - name: http
    port: 8080
    nodePort: 30080
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: person-api

spec:
  selector:
    matchLabels:
      app: person-api
  replicas: 3
  template:
    metadata:
      labels:
        app: person-api
    spec:
      containers:
        - name: person-api
          image: prakum/person-api:${BUILD_NUMBER}
